Feature/sketch
lorawan-academy/week7 pull request #2
Opened 2017-11-16 11:55 UTC by Yerion

Sketch branch is ready for review

2017-11-16 12:19 UTC, johanstokking requested changes
- Use lowercase folder names everywhere
- Don't use big comment blocks with those `*****`
- Use a code formatter that takes care of spaces and tabs. Install a proper plugin in your editor and configure it correctly. Hint: the code snippets in the README are messy, also mixing things like `char *x` and `char* x`
- Look at the commit messages; fixup, commit amend, reword, etc, make sure it's clean
- Don't add Dutch screenshots

2017-11-20 17:18 UTC, johanstokking commented
Reopen when it's ready to review.

Few things at first sight:
- Indentation is still not good
- Commit messages follow: `low: Description`. Please reword this branch
- Group connector instructions together, preferably not in the code but in corresponding documentation
- Don't globally declare variables when that is not necessary

2017-11-20 17:19 UTC, closed without merging

2017-11-21 08:27 UTC, Yerion commented
* Indentation is still not good
Where am I messing up? I can't see it.
* Commit messages follow: low: Description. Please reword this branch
What do you mean with: low?
* Group connector instructions together, preferably not in the code but in corresponding documentation
Do you mean comments like these: // When using the sodaq explorer connect the ESP TX to pin D0 and RX to D1?

2017-11-22 15:05 UTC, johanstokking reviewed
See below for some examples.

With commit messages, I mean that the first part is lowercase and refers to something, for example `sketch`, `doc`, etc. No branch names, no uppercase, no inconsistencies.

Indeed those comments.

2017-11-22 15:05 UTC, johanstokking commented on Sketch/payload.js
> +	var Bssid3 = [6];
- What is this?
- Also use lowercase variable names

2017-11-22 15:05 UTC, johanstokking commented on Sketch/payload.js
> +	for(i = 0, j = 0; i < 6 && j < 6; i++, j++)
Turn this into a function you call three times

2017-11-22 15:05 UTC, johanstokking commented on Sketch/payload.js
> +	decoded.Bssid1 = Bssid1.join('') ;
Formatting

2017-11-22 15:05 UTC, johanstokking commented on Sketch/payload.js
> +return  (n < 10 || n == 'a' || n =='b' || n == 'c' || n == 'd' || n == 'e' || n == 'f' ) ? ("0" + n) : n;
Formatting and indentation

2017-11-22 15:05 UTC, johanstokking commented on Sketch/README.md
> +  espSerial.begin (9600); //Possible baud rates to try: 9600, 19200, 38400, 57600. Don’t forget to change the baud rate in the serial monitor accordingly
Formatting and put instruction in setup doc

2017-11-22 15:05 UTC, johanstokking commented on Sketch/README.md
> +    while (millis() < timeout)
Indentation

2017-11-22 15:05 UTC, johanstokking commented on Sketch/README.md
> +        if (l > 0 && strncmp("OK", buffer, 2) == 0)
Indentation, many other occurrences in this file

2017-11-22 15:05 UTC, johanstokking commented on Sketch/Explorer_ESP_WiFi-localization_v1.2.ino
> +	debugSerial.println("Restart the loop");
Indentation

2017-11-22 15:05 UTC, johanstokking commented on Sketch/Explorer_ESP_WiFi-localization_v1.2.ino
> +// Break the accesspoint in tokens, to get the bssid out.
Indentation